# Enable C++ support
language: cpp

os: linux
dist: bionic
sudo: required

compiler:
  - clang
  - gcc

install:
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]
    then
      sudo apt-get -y install qt5-default libboost-all-dev libcgal-dev libgmp-dev libqglviewer-dev-qt5 libeigen3-dev      
    fi
  - git clone --recursive https://github.com/cg3hci/cg3lib

script:
  - cd cg3lib/examples
  - qmake examples.pro
  - make
