# Enable C++ support
language: cpp

os: linux
dist: bionic
sudo: required

compiler:
  - clang
  - gcc

install:
  - sudo apt-get -y install qt5-default libboost-all-dev libcgal-dev libgmp-dev libqglviewer-dev-qt5 libeigen3-dev      
  - cd ..
  - git clone --recursive https://github.com/libigl/libigl
  - ls libigl/
  - env LIBIGL_HOME=$(pwd)/libigl/
  - echo $LIBIGL_HOME

script:
  - cd cg3lib/examples
  - qmake examples.pro
  - make
