name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: installing dependencies
      run: |
           sudo apt update
           sudo apt -y install qt5-default libboost-all-dev libcgal-dev libgmp-dev libqglviewer-dev-qt5 libeigen3-dev
           cd ..
           git clone --recursive https://github.com/libigl/libigl
           ls libigl/
           export LIBIGL_HOME=$(pwd)/libigl/
    - name: compiling examples
      run: |
           cd cg3lib/examples
           qmake examples.pro
           make
      
