name: MacOSClang

on: [push, pull_request]

jobs:
  build:

    runs-on: macos
    
    steps:
    - uses: actions/checkout@v1
    - name: installing dependencies
      run: |
            brew install qt cgal llvm
            #install libQGLViewer
            export QTDIR=/usr/local/opt/qt
            export PATH=$QTDIR/bin:$PATH
            export LD_LIBRARY_PATH=$QTDIR/lib:$LD_LIBRARY_PATH
            export PKG_CONFIG_PATH=$QTDIR/lib:$PKG_CONFIG_PATH
            cd ..
            git clone https://github.com/GillesDebunne/libQGLViewer.git
            cd libQGLViewer/QGLViewer
            qmake
            make 
            make install            
            cd ..
            cd ..
            #install libigl
            git clone --recursive https://github.com/libigl/libigl
    - name: compiling examples
      run: |
            export QTDIR=/usr/local/opt/qt
            export PATH=$QTDIR/bin:$PATH
            export LD_LIBRARY_PATH=$QTDIR/lib:$LD_LIBRARY_PATH
            export PKG_CONFIG_PATH=$QTDIR/lib:$PKG_CONFIG_PATH
            export QGLVIEWER_HOME=/usr/local/lib #here is installed QGLViewer.framework
            export LIBIGL_HOME=$(pwd)/../libigl/
            cd examples
            qmake examples.pro
            make
